services:
  - type: web
    name: toolbase-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: APPWRITE_ENDPOINT
        sync: false
      - key: APPWRITE_PROJECT
        sync: false
      - key: APPWRITE_API_KEY
        sync: false
      - key: ADMIN_EMAILS
        value: admin@toolbase.app
      - key: ALLOWED_ORIGINS
        sync: false
